### ISSUE TITLE
Threshold length for curve shortening with EdgeFlipGeodesicSolver

### ISSUE THREAD

**Issue by areiner222** [nmwsharp/potpourri3d#14]
Thanks for this great work! 
I'm not an expert in 3D geometry and searched for a while until I found your geodesic path implementation. Exactly what I need!

I want to use the EdgeFlipGeodesicSolver to straighten jagged loops for mesh segmentation, but some of my loops can be reduced to a point so I think I need to set the threshold length as described in your paper. Is there any way this can be exposed with the python api?

**Comment by nmwsharp** [comment]
A bit delayed, but this is now added in [7b22940](https://github.com/nmwsharp/potpourri3d/commit/7b2294018d9c86c3f6bdf1512265714c66074c56). New python version will be deployed soon. Thanks for the suggestion!
