### ISSUE TITLE
Geodesic from a predefined path?

### ISSUE THREAD

**Issue by panangam** [nmwsharp/potpourri3d#2]
Thank you so much for making the python binding! I use mainly use python for geometry stuff, so this is extremely helpful.

I'm working on some anthropometry, and trying to extract the rise curve, from the navel down the crotch and up to the lower back. I'm trying to use the edge flip solver for this, but the shorter path it found is around the side of the torso. According to the paper, it seems it should be possible to optimize a path through a different direction. Would that be possible to do with the python binding? 
<img width="573" alt="Screen Shot 2021-05-27 at 10 22 20 AM" src="https://user-images.githubusercontent.com/17264683/119869746-737fd100-bed5-11eb-9fe6-590163baa721.png">

**Comment by nmwsharp** [comment]
Hi! Glad this is useful for you!

You're right that this is certainly possible with the flip geodesic method, but previously it was not exposed in the bindings.

I've just added a new function to the bindings called `find_geodesic_path_poly()` which takes a input a _list_ of vertices, finds an initial path by running Dijkstra between each consecutive vertex, then straightens that path to be a geodesic.

We can use it for your example by passing as input a list of three vertices `path = solver.find_geodesic_path_poly([v_start, v_middle, v_end])`, where `v_start` is on the navel, `v_middle` is near the crotch, and `v_end` is on the lower back. This gives me the result below.

![screenshot_000000](https://user-images.githubusercontent.com/12726725/120045624-72869680-bfde-11eb-928d-2b3b57099fef.jpg)


The CI system is currently building a new version of the library with this function added, should be available on pip soon.

**Comment by panangam** [comment]
This is perfect, thank you! Gonna close then.
